from .home import home_bp
from .auth import auth_bp
from .profile import profile_bp
from .food import food_bp
from .cart import cart_bp
from .checkout import checkout_bp
from .order import orders_bp
from .payment import payment_bp
from .admin import admin_bp